Fix: build error with amrex_sundials_advection_diffusion with cuda
ld: /data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/amrex-22.09-6ce3ym3r5jw6px7gukhsjpepjt3ivcl5/lib/libamrex.a(AMReX_ParallelDescriptor.cpp.o): undefined reference to symbol 'MPI_Barrier'
/data/balay/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/openmpi-4.1.5-tqpwhe5c45zo6jctlzultir54v4msztk/lib/libmpi.so.40: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [amrex/sundials/CMakeFiles/amrex_sundials_advection_diffusion.dir/build.make:159: amrex/sundials/amrex_sundials_advection_diffusion] Error 1

Ref: https://github.com/xsdk-project/xsdk-examples/pull/42#issuecomment-1541626218